version: '2'

services:
  nginx:
    image: nginx:1.11
    restart: always
    volumes_from:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - "8080:80"

  app:
    build: ./
    volumes:
      - ./:/var/www
    links:
      - mysql:db
    restart: always
    env_file:
      - ./.env
    group_add:
      - www-data
    environment:
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_DATABASE=dnswrapper
      - DB_PASSWORD=dnswrapper

  mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=dnswrapper
        - MYSQL_DATABASE=dnswrapper
      ports:
        - "33061:3306"
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data: