version: '2'

services:
  https-portal:
    image: steveltn/https-portal:1.0.0
    ports:
      - "80:80"
      - "443:443"
    restart: always
    links:
      - nginx
    environment:
      STAGE: "production"
      DOMAINS: "staging.dns.jcrocker.uk -> http://nginx"