<?php declare(strict_types=1);

namespace Jrdn\DoApiWrapper\Infrastructure\Services\DigitalOcean\Auth;

use ChrisHemmings\OAuth2\Client\Provider\DigitalOcean;

/**
 * Class Provider
 *
 * @author jrdn hannah <jrdn@jrdnhannah.co.uk>
 */
final class Provider extends DigitalOcean
{
    protected function getDefaultScopes()
    {
        return parent::getDefaultScopes(); // TODO: Change the autogenerated stub
    }

}